import Head from "next/head";
import {Layout} from "../components"

export default function Home() {
    return (
      <div>
        <Head>
          <title>ProjetoTCC</title>
          <meta name="description" content="Generated by create nex app"/>
          <link rel="stylesheet" href="/favicon.ico" />
        </Head>

        <Layout/>
      </div>
    );
  }
  